"""add open_type column for trade table

Revision ID: 8f78e97382b0
Revises: d846c862f2eb
Create Date: 2022-07-22 23:24:34.289377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f78e97382b0'
down_revision = 'd846c862f2eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('open_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade', 'open_type')
    # ### end Alembic commands ###
